title: Robb Lewis Media
description: "List of movies, TV shows, books and games I've consumed"

# Build settings
permalink: pretty
paginate: 50
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
